export type Country = { en: string; th: string };

/** Full world country/territory list (English + Thai names), used for filters
 *  that must offer every country regardless of which ones currently have data
 *  (e.g. campaign targeting) — unlike lists derived from existing member records. */
export const WORLD_COUNTRIES: Country[] = [
  { en: "Afghanistan", th: "อัฟกานิสถาน" },
  { en: "Åland Islands", th: "หมู่เกาะโอลันด์" },
  { en: "Albania", th: "แอลเบเนีย" },
  { en: "Algeria", th: "แอลจีเรีย" },
  { en: "American Samoa", th: "อเมริกันซามัว" },
  { en: "Andorra", th: "อันดอร์รา" },
  { en: "Angola", th: "แองโกลา" },
  { en: "Anguilla", th: "แองกวิลลา" },
  { en: "Antarctica", th: "แอนตาร์กติกา" },
  { en: "Antigua and Barbuda", th: "แอนติกาและบาร์บูดา" },
  { en: "Argentina", th: "อาร์เจนตินา" },
  { en: "Armenia", th: "อาร์เมเนีย" },
  { en: "Aruba", th: "อารูบา" },
  { en: "Ascension Island", th: "เกาะแอสเซนเชียน" },
  { en: "Australia", th: "ออสเตรเลีย" },
  { en: "Austria", th: "ออสเตรีย" },
  { en: "Azerbaijan", th: "อาเซอร์ไบจาน" },
  { en: "Bahamas", th: "บาฮามาส" },
  { en: "Bahrain", th: "บาห์เรน" },
  { en: "Bangladesh", th: "บังคลาเทศ" },
  { en: "Barbados", th: "บาร์เบโดส" },
  { en: "Belarus", th: "เบลารุส" },
  { en: "Belgium", th: "เบลเยียม" },
  { en: "Belize", th: "เบลีซ" },
  { en: "Benin", th: "เบนิน" },
  { en: "Bermuda", th: "เบอร์มิวดา" },
  { en: "Bhutan", th: "ภูฏาน" },
  { en: "Bolivia", th: "รัฐพหุชนชาติแห่งโบลิเวีย" },
  { en: "Bosnia and Herzegovina", th: "บอสเนียและเฮอร์เซโกวินา" },
  { en: "Botswana", th: "บอตสวานา" },
  { en: "Bouvet Island", th: "เกาะบูเวต" },
  { en: "Brazil", th: "บราซิล" },
  { en: "British Indian Ocean Territory", th: "ดินแดนของอังกฤษในมหาสมุทรอินเดีย" },
  { en: "British Virgin Islands", th: "หมู่เกาะเวอร์จิน (สหราชอาณาจักร)" },
  { en: "Brunei", th: "เนการาบรูไนดารุสซาลาม" },
  { en: "Bulgaria", th: "บัลแกเรีย" },
  { en: "Burkina Faso", th: "บูร์กินาฟาโซ" },
  { en: "Burundi", th: "บุรุนดี" },
  { en: "Cambodia", th: "กัมพูชา" },
  { en: "Cameroon", th: "แคเมอรูน" },
  { en: "Canada", th: "แคนาดา" },
  { en: "Cape Verde", th: "เคปเวิร์ด" },
  { en: "Cayman Islands", th: "หมู่เกาะเคย์แมน" },
  { en: "Central African Republic", th: "สาธารณรัฐแอฟริกากลาง" },
  { en: "Chad", th: "ชาด" },
  { en: "Chile", th: "ชิลี" },
  { en: "China", th: "จีน" },
  { en: "Christmas Island", th: "เกาะคริสต์มาส" },
  { en: "Cocos (Keeling) Islands", th: "หมู่เกาะโคโคส (คีลิง)" },
  { en: "Colombia", th: "โคลัมเบีย" },
  { en: "Comoros", th: "คอโมโรส" },
  { en: "Congo (Brazzaville)", th: "คองโก" },
  { en: "Congo (Kinshasa)", th: "สาธารณรัฐประชาธิปไตยคองโก" },
  { en: "Cook Islands", th: "หมู่เกาะคุก" },
  { en: "Costa Rica", th: "คอสตาริกา" },
  { en: "Croatia", th: "โครเอเชีย" },
  { en: "Cuba", th: "คิวบา" },
  { en: "Curaçao", th: "คูราเซา" },
  { en: "Cyprus", th: "ไซปรัส" },
  { en: "Czechia", th: "เช็กเกีย" },
  { en: "Denmark", th: "เดนมาร์ก" },
  { en: "Djibouti", th: "จิบูตี" },
  { en: "Dominica", th: "โดมินิกา" },
  { en: "Dominican Republic", th: "สาธารณรัฐโดมินิกัน" },
  { en: "Ecuador", th: "เอกวาดอร์" },
  { en: "Egypt", th: "อียิปต์" },
  { en: "El Salvador", th: "เอลซัลวาดอร์" },
  { en: "Equatorial Guinea", th: "อิเควทอเรียลกินี" },
  { en: "Eritrea", th: "เอริเทรีย" },
  { en: "Estonia", th: "เอสโตเนีย" },
  { en: "Eswatini", th: "ราชอาณาจักรเอสวาตินี" },
  { en: "Ethiopia", th: "เอธิโอเปีย" },
  { en: "Falkland Islands", th: "หมู่เกาะฟอล์กแลนด์" },
  { en: "Faroe Islands", th: "หมู่เกาะแฟโร" },
  { en: "Fiji", th: "ฟิจิ" },
  { en: "Finland", th: "ฟินแลนด์" },
  { en: "France", th: "ฝรั่งเศส" },
  { en: "French Guiana", th: "เฟรนช์เกียนา" },
  { en: "French Polynesia", th: "เฟรนช์พอลินีเซีย" },
  { en: "French Southern Territories", th: "เฟรนช์เซาเทิร์นเทร์ริทอรีส์" },
  { en: "Gabon", th: "กาบอง" },
  { en: "Gambia", th: "แกมเบีย" },
  { en: "Georgia", th: "จอร์เจีย" },
  { en: "Germany", th: "เยอรมนี" },
  { en: "Ghana", th: "กานา" },
  { en: "Gibraltar", th: "ยิบรอลตาร์" },
  { en: "Greece", th: "กรีซ" },
  { en: "Greenland", th: "กรีนแลนด์" },
  { en: "Grenada", th: "เกรเนดา" },
  { en: "Guadeloupe", th: "กัวเดอลูป" },
  { en: "Guam", th: "กวม" },
  { en: "Guatemala", th: "กัวเตมาลา" },
  { en: "Guernsey", th: "เกิร์นซีย์" },
  { en: "Guinea", th: "กินี" },
  { en: "Guinea-Bissau", th: "กินี-บิสเซา" },
  { en: "Guyana", th: "กายอานา" },
  { en: "Haiti", th: "เฮติ" },
  { en: "Heard Island and McDonald Islands", th: "เกาะเฮิร์ดและหมู่เกาะแมกโดนัลด์" },
  { en: "Honduras", th: "ฮอนดูรัส" },
  { en: "Hong Kong SAR", th: "เขตบริหารพิเศษฮ่องกง" },
  { en: "Hungary", th: "ฮังการี" },
  { en: "Iceland", th: "ไอซ์แลนด์" },
  { en: "India", th: "อินเดีย" },
  { en: "Indonesia", th: "อินโดนีเซีย" },
  { en: "Iran", th: "อิหร่าน" },
  { en: "Iraq", th: "อิรัก" },
  { en: "Ireland", th: "ไอร์แลนด์" },
  { en: "Isle of Man", th: "ไอล์ออฟแมน" },
  { en: "Israel", th: "อิสราเอล" },
  { en: "Italy", th: "อิตาลี" },
  { en: "Ivory Coast", th: "โกตดิวัวร์" },
  { en: "Jamaica", th: "จาเมกา" },
  { en: "Japan", th: "ญี่ปุ่น" },
  { en: "Jersey", th: "เจอร์ซีย์" },
  { en: "Jordan", th: "จอร์แดน" },
  { en: "Kazakhstan", th: "คาซัคสถาน" },
  { en: "Kenya", th: "เคนยา" },
  { en: "Kiribati", th: "คิริบาส" },
  { en: "Kosovo", th: "โคโซโว" },
  { en: "Kuwait", th: "คูเวต" },
  { en: "Kyrgyzstan", th: "คีร์กีซสถาน" },
  { en: "Laos", th: "ลาว" },
  { en: "Latvia", th: "ลัตเวีย" },
  { en: "Lebanon", th: "เลบานอน" },
  { en: "Lesotho", th: "เลโซโท" },
  { en: "Liberia", th: "ไลบีเรีย" },
  { en: "Libya", th: "ลิเบีย" },
  { en: "Liechtenstein", th: "ลิกเตนสไตน์" },
  { en: "Lithuania", th: "ลิทัวเนีย" },
  { en: "Luxembourg", th: "ลักเซมเบิร์ก" },
  { en: "Macao SAR", th: "เขตบริหารพิเศษมาเก๊า" },
  { en: "Madagascar", th: "มาดากัสการ์" },
  { en: "Malawi", th: "มาลาวี" },
  { en: "Malaysia", th: "มาเลเซีย" },
  { en: "Maldives", th: "มัลดีฟส์" },
  { en: "Mali", th: "มาลี" },
  { en: "Malta", th: "มอลตา" },
  { en: "Marshall Islands", th: "หมู่เกาะมาร์แชลล์" },
  { en: "Martinique", th: "มาร์ตินีก" },
  { en: "Mauritania", th: "มอริเตเนีย" },
  { en: "Mauritius", th: "มอริเชียส" },
  { en: "Mayotte", th: "มายอต" },
  { en: "Mexico", th: "เม็กซิโก" },
  { en: "Micronesia", th: "สหพันธรัฐไมโครนีเซีย" },
  { en: "Moldova", th: "มอลโดวา" },
  { en: "Monaco", th: "โมนาโก" },
  { en: "Mongolia", th: "มองโกเลีย" },
  { en: "Montenegro", th: "มอนเตเนโกร" },
  { en: "Montserrat", th: "มอนต์เซอร์รัต" },
  { en: "Morocco", th: "โมร็อกโก" },
  { en: "Mozambique", th: "โมซัมบิก" },
  { en: "Myanmar", th: "พม่า" },
  { en: "Namibia", th: "นามิเบีย" },
  { en: "Nauru", th: "นาอูรู" },
  { en: "Nepal", th: "เนปาล" },
  { en: "Netherlands", th: "เนเธอร์แลนด์" },
  { en: "New Caledonia", th: "นิวแคลิโดเนีย" },
  { en: "New Zealand", th: "นิวซีแลนด์" },
  { en: "Nicaragua", th: "นิการากัว" },
  { en: "Niger", th: "ไนเจอร์" },
  { en: "Nigeria", th: "ไนจีเรีย" },
  { en: "Niue", th: "นีอูเอ" },
  { en: "Norfolk Island", th: "เกาะนอร์โฟล์ก" },
  { en: "North Korea", th: "เกาหลีเหนือ" },
  { en: "North Macedonia", th: "มาซิโดเนียเหนือ" },
  { en: "Northern Mariana Islands", th: "หมู่เกาะนอร์เทิร์นมาเรียนา" },
  { en: "Norway", th: "นอร์เวย์" },
  { en: "Oman", th: "โอมาน" },
  { en: "Pakistan", th: "ปากีสถาน" },
  { en: "Palau", th: "ปาเลา" },
  { en: "Palestine", th: "รัฐปาเลสไตน์" },
  { en: "Panama", th: "ปานามา" },
  { en: "Papua New Guinea", th: "ปาปัวนิวกินี" },
  { en: "Paraguay", th: "ปารากวัย" },
  { en: "Peru", th: "เปรู" },
  { en: "Philippines", th: "ฟิลิปปินส์" },
  { en: "Pitcairn Islands", th: "หมู่เกาะพิตแคร์น" },
  { en: "Poland", th: "โปแลนด์" },
  { en: "Portugal", th: "โปรตุเกส" },
  { en: "Puerto Rico", th: "เปอร์โตริโก" },
  { en: "Qatar", th: "กาตาร์" },
  { en: "Réunion", th: "เรอูนียง" },
  { en: "Romania", th: "โรมาเนีย" },
  { en: "Russia", th: "สหพันธรัฐรัสเซีย" },
  { en: "Rwanda", th: "รวันดา" },
  { en: "Saint Barthélemy", th: "แซ็ง บาร์เตเลมี" },
  { en: "Saint Helena", th: "เซนต์เฮเลนา และตริสตันดากูนยา" },
  { en: "Saint Kitts and Nevis", th: "เซนต์คิตส์และเนวิส" },
  { en: "Saint Lucia", th: "เซนต์ลูเซีย" },
  { en: "Saint Martin (French)", th: "แซงมาร์แต็ง (ฝรั่งเศส)" },
  { en: "Saint Pierre and Miquelon", th: "แซงปีแยร์และมีเกอลง" },
  { en: "Saint Vincent and the Grenadines", th: "เซนต์วินเซนต์และเกรนาดีน" },
  { en: "Samoa", th: "ซามัว" },
  { en: "San Marino", th: "ซานมารีโน" },
  { en: "São Tomé and Príncipe", th: "เซาตูเมและปรินซิปี" },
  { en: "Saudi Arabia", th: "ซาอุดีอาระเบีย" },
  { en: "Senegal", th: "เซเนกัล" },
  { en: "Serbia", th: "เซอร์เบีย" },
  { en: "Seychelles", th: "เซเชลส์" },
  { en: "Sierra Leone", th: "เซียร์ราลีโอน" },
  { en: "Singapore", th: "สิงคโปร์" },
  { en: "Sint Maarten (Dutch)", th: "ซินต์มาร์เติน (ดัตช์)" },
  { en: "Slovakia", th: "สโลวาเกีย" },
  { en: "Slovenia", th: "สโลวีเนีย" },
  { en: "Solomon Islands", th: "หมู่เกาะโซโลมอน" },
  { en: "Somalia", th: "โซมาเลีย" },
  { en: "South Africa", th: "แอฟริกาใต้" },
  { en: "South Georgia and the South Sandwich Islands", th: "เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช" },
  { en: "South Korea", th: "เกาหลีใต้" },
  { en: "South Sudan", th: "ซูดานใต้" },
  { en: "Spain", th: "สเปน" },
  { en: "Sri Lanka", th: "ศรีลังกา" },
  { en: "Sudan", th: "ซูดาน" },
  { en: "Suriname", th: "ซูรินาเม" },
  { en: "Svalbard and Jan Mayen", th: "สฟาลบาร์และยานไมเอน" },
  { en: "Sweden", th: "สวีเดน" },
  { en: "Switzerland", th: "สวิตเซอร์แลนด์" },
  { en: "Syria", th: "ซีเรีย" },
  { en: "Taiwan", th: "รัฐบาลสาธารณรัฐจีน (ไต้หวัน)" },
  { en: "Tajikistan", th: "ทาจิกิสถาน" },
  { en: "Tanzania", th: "แทนซาเนีย" },
  { en: "Thailand", th: "ไทย" },
  { en: "Timor-Leste", th: "ติมอร์-เลสเต" },
  { en: "Togo", th: "โทโก" },
  { en: "Tokelau", th: "โตเกเลา" },
  { en: "Tonga", th: "ตองกา" },
  { en: "Trinidad and Tobago", th: "ตรินิแดดและโตเบโก" },
  { en: "Tunisia", th: "ตูนิเซีย" },
  { en: "Turkey", th: "ตุรกี" },
  { en: "Turkmenistan", th: "เติร์กเมนิสถาน" },
  { en: "Turks and Caicos Islands", th: "หมู่เกาะเติกส์และเคคอส" },
  { en: "Tuvalu", th: "ตูวาลู" },
  { en: "Uganda", th: "ยูกันดา" },
  { en: "Ukraine", th: "ยูเครน" },
  { en: "United Arab Emirates", th: "สหรัฐอาหรับเอมิเรตส์" },
  { en: "United Kingdom", th: "สหราชอาณาจักร" },
  { en: "United States", th: "สหรัฐอเมริกา" },
  { en: "United States Minor Outlying Islands", th: "เกาะเล็กรอบนอกของสหรัฐอเมริกา" },
  { en: "Uruguay", th: "อุรุกวัย" },
  { en: "Uzbekistan", th: "อุซเบกิสถาน" },
  { en: "Vanuatu", th: "วานูอาตู" },
  { en: "Vatican City", th: "นครรัฐวาติกัน (Holy See)" },
  { en: "Venezuela", th: "เวเนซุเอลา" },
  { en: "Vietnam", th: "เวียดนาม" },
  { en: "Wallis and Futuna", th: "วาลลิสและฟูตูนา" },
  { en: "Western Sahara", th: "ซาฮาราตะวันตก" },
  { en: "Yemen", th: "เยเมน" },
  { en: "Zambia", th: "แซมเบีย" },
  { en: "Zimbabwe", th: "ซิมบับเว" },
];
